---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liferay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: liferay
  template:
    metadata:
      labels:
        app: liferay
        app.kubernetes.io/name: liferay
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - name: liferay
        image: liferay/portal:7.4.3.48-ga48
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: liferay-service
spec:
  selector:
    app.kubernetes.io/name: liferay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
