apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-java-auto-instrumentation
spec:
  exporter:
    endpoint: http://$(OTEL_NODE_IP):4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
